version: "3"

# Docker-compose creates a network for all the other docker images to join, forming a cluster.
# Network name will be that of the parent directory name.

services:
  master:
    build: .
    image: davidainslie/spark
    container_name: master
    ports:
      - 4040:4040
      - 7077:7077
      - 8080:8080
      - 6066:6066
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/master.conf"]

  slave:
    image: davidainslie/spark
    depends_on:
      - master
    ports:
      - 8081
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/slave.conf"]
    volumes:
      - ./data/output/:/opt/output
      - ./data/events/:/opt/spark-events

  history-server:
    image: davidainslie/spark
    container_name: history-server
    depends_on:
      - master
    ports:
      - 18080:18080
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/history-server.conf"]
    volumes:
      - ./data/events:/opt/spark-events