version: "3.7"

services:
  # docker run -p5432:5432 -d tpolecat/skunk-world
  postgres:
    image: tpolecat/skunk-world
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql